### Project specific config ###
dist: trusty
language: ruby

matrix:
  include:
    - os: linux
      rvm: 2.3.4

    - os: linux
      rvm: 2.3.4
      env: ATOM_CHANNEL=beta

env:
  global:
    APM_TEST_PACKAGES: "language-puppet"

install:
  - gem install --no-document puppet-lint

before_script:
  - puppet-lint --version

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
