### Project specific config ###
environment:
  APM_TEST_PACKAGES: language-puppet
  RUBY_VERSION: 23-x64

  matrix:
    - ATOM_CHANNEL: stable
    - ATOM_CHANNEL: beta

install:
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem update --system
  - gem install puppet-lint --no-document

before_build:
  - ruby --version
  - gem --version
  - puppet-lint --version

### Generic setup follows ###
build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

branches:
  only:
    - master

version: "{build}"
platform: x64
clone_depth: 10
skip_tags: true
test: off
deploy: off
