module.exports = {
  automaticFix: '-f',
  skipRightToLeftRelationship: '--no-right_to_left_relationship-check',
  skipAutoloaderLayout: '--no-autoloader_layout-check',
  skipNamesContainingDash: '--no-names_containing_dash-check',
  skipClassInherithsFromParamClass: '--no-class_inherits_from_params_class-check',
  skipParameterOrder: '--no-parameter_order-check ',
  skipInheritsAcrossNamespaces: '--no-inherits_across_namespaces-check',
  skipNestedClassesOrDefines: '--no-nested_classes_or_defines-check',
  skipVariableScope: '--no-variable_scope-check',
  skipSlashComments: '--no-slash_comments-check',
  skipStarComments: '--no-star_comments-check',
  skipSelectorInsideResource: '--no-selector_inside_resource-check',
  skipCaseWithoutDefault: '--no-case_without_default-check',
  skipDocumentation: '--no-documentation-check',
  skipDoubleQuotedStrings: '--no-double_quoted_strings-check',
  skipOnlyVariableString: '--no-only_variable_string-check',
  skipVariablesNotEnclosed: '--no-variables_not_enclosed-check',
  skipSingleQuoteStringWithVariables: '--no-single_quote_string_with_variables-check',
  skipQuotedBooleans: '--no-quoted_booleans-check',
  skipPuppetUrlWhitoutModules: '--no-puppet_url_without_modules-check',
  skipVariableContainsDash: '--no-variable_contains_dash-check',
  skipHardTabs: '--no-hard_tabs-check',
  skipTrailingWhitespace: '--no-trailing_whitespace-check',
  skip80Chars: '--no-80chars-check',
  skip140Chars: '--no-140chars-check',
  skip2spSoftTabs: '--no-2sp_soft_tabs-check',
  skipArrowAlignment: '--no-arrow_alignment-check',
  skipUnquotedResourceTitle: '--no-unquoted_resource_title-check',
  skipEnsureFirstParam: '--no-ensure_first_param-check',
  skipDuplicateParams: '--no-duplicate_params-check',
  skipUnquotedFileMode: '--no-unquoted_file_mode-check',
  skipFileMode: '--no-file_mode-check',
  skipEnsureNotSymlinkTarget: '--no-ensure_not_symlink_target-check',
  skipUnquotedNodeName: '--no-unquoted_node_name-check',
};
